### ISSUE TITLE
Adjust folder structure

### ISSUE THREAD

**Issue by zakiego** [zakiego/telegram-bot-gitlab#3]
https://github.com/zakiego/telegram-bot-gitlab#folder-structure

**Comment by ahmedelbilal** [comment]
I would like to take this

**Comment by zakiego** [comment]
Ok, just move `utils/gitlab` to `handler`

**Comment by zakiego** [comment]
[!9](https://github.com/zakiego/telegram-bot-gitlab/pull/9)
